---
name: Test GitHub Actions
"on":
  workflow_call:
    inputs:
      github-token:
        required: true
        type: string

jobs:
  test-actions:
    name: Test GitHub Actions
    runs-on: ubuntu-24.04
    permissions:
      checks: write
      contents: read
      pull-requests: write
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: reviewdog/action-yamllint@b5f7217d8c815ae374d1d55840d5e569d82f01f0 # v1.22.0
        with:
          fail_level: error
          reporter: github-pr-review
      - uses: ne-sachirou/lint-gha-reviewdog@21e9e3be880468f3fceff09b97e02094eb000a43 # v0.0.6
        with:
          github_token: ${{ inputs['github-token'] }}
