---
name: Test GitHub Actions
"on":
  workflow_call:
    inputs:
      github-token:
        required: true
        type: string

jobs:
  test-actions:
    name: Test GitHub Actions
    runs-on: ubuntu-24.04
    permissions:
      checks: write
      contents: read
      pull-requests: write
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: reviewdog/action-yamllint@f01d8a48fd8d89f89895499fca2cff09f9e9e8c0 # v1.21.0
        with:
          fail_level: error
          reporter: github-pr-review
      - uses: ne-sachirou/lint-gha-reviewdog@47315c74bcffa1c74c12a6e1f004bf6e1fd4147b # v0.0.1
        with:
          github_token: ${{ inputs['github-token'] }}
