---
name: Test Go
"on":
  workflow_call:

jobs:
  test-go:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    timeout-minutes: 10
    strategy:
      matrix:
        go: ["1.25", "1.26"]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: ${{ matrix.go }}
      - uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
      - name: go generate の生成漏れが無いか確認
        run: |
          set -e
          go generate ./...
          git diff --exit-code
      - name: go build
        run: |
          (cd cmd/example && go build -o main main.go) || exit 1
          (cd cmd/example-grpc && go build -o main main.go) || exit 1
          (cd cmd/example-http && go build -o main main.go) || exit 1
      - name: go test
        run: go test ./...
      - uses: golang/govulncheck-action@032d45514ae346b1db93c04b0c90b841c370344f # v1.1.0
        with:
          repo-checkout: false
